DROP TABLE MASCOTAS
DROP TABLE USUARIOS

CREATE TABLE USUARIOS(
 ID     INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 NOMBRE VARCHAR(50) NOT NULL,
 FNAC   DATE NOT NULL,
 EMAIL  VARCHAR(255) DEFAULT '',
 MAP    DECIMAL(4,2) DEFAULT 0,
 NOTAS  TEXT DEFAULT ''
);

CREATE TABLE MASCOTAS(
 ID            INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 IDPROPIETARIO INT NOT NULL REFERENCES USUARIOS (ID) ON DELETE CASCADE,
 NOMBRE        VARCHAR(50) NOT NULL,
 FNAC          DATE NOT NULL
);

INSERT INTO USUARIOS 
(NOMBRE, FNAC, EMAIL, MAP) VALUES 
('USUARIO#3', '2000-07-16', 'us1@email.com', 2.34);
SELECT IDENT_CURRENT('USUARIOS')

INSERT INTO MASCOTAS
(IDPROPIETARIO, NOMBRE, FNAC) VALUES
(1, 'TIGGER', '2000-07-16')

SELECT * 
FROM USUARIOS U INNER JOIN MASCOTAS M 
ON U.ID=M.IDPROPIETARIO;
